config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  namespace :api do
    namespace :v1 do
      resources :reservations
    end
  end
  root 'reservations#index'

  match '*unmatched', to: proc { [404, {}, ['Invalid route']] }, via: :all
end

app/models/reservation.rb
class Reservation
  include Mongoid::Document
  field :id, type: String
  field :hotel_name, type: String
  field :price, type: Float
  field :currency, type: String
  field :arrival_date, type: Date
  field :departure_date, type: Date
  field :guest_name, type: String
  field :guest_email, type: String

  validates_presence_of :hotel_name, :price, :currency, :arrival_date, :departure_date,
                        :guest_name, :guest_email
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
      before_action :set_default_format

      private

      def set_default_format
        request.format = :json
      end
    end
  end
end

app/controllers/api/v1/reservations_controller.rb
module Api
  module V1
    class ReservationsController < ApiController
      before_action :set_reservation, only: %i[ show update destroy ]
      def index
        reservations = Reservation.all

        render locals: { reservations: reservations }
      end

      def show
        render :show, locals: { reservation: @reservation }
      end

      def create
        reservation = Reservation.new(reservation_params)
        if reservation.save
          render :show, locals: { reservation: reservation }
        else
          render json: reservation.errors, status: :unprocessable_entity
        end
      end

      def update
        if @reservation.update(reservation_params)
          render :show, locals: { reservation: @reservation }
        else
          render json: @reservation.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @reservation.destroy!

        head :no_content
      end

      private

      def set_reservation
        @reservation = Reservation.find(params[:id])
      end

      def reservation_params
        params.require(:reservation).permit(
          %i(hotel_name price currency arrival_date departure_date guest_name guest_email)
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def edit
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end



  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      %i(hotel_name price currency arrival_date departure_date guest_name guest_email)
    )
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>HotelBookingManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<div class="container">
  <%= form_with(model: reservation) do |form| %>
    <% if reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
          <% reservation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="row g-3">
      <div class="mb-12">
        <%= form.label :hotel_name, :class => "form-label" %>
        <%= form.text_field :hotel_name, :class => "form-control", :placeholder => "Hotel Name" %>
      </div>

      <div class="col-md-6">
        <%= form.label :price, :class => "form-label" %>
        <%= form.text_field :price, :class => "form-control", :placeholder => "200.00" %>
      </div>

      <div class="col-md-6">
        <%= form.label :currency, :class => "form-label" %>
        <%= form.text_field :currency, :class => "form-control", :placeholder => "euro" %>
      </div>
      <div class="mb-12">
        <%= form.label :guest_name, :class => "form-label" %>
        <%= form.text_field :guest_name, :class => "form-control", :placeholder => "Jack reacher" %>
      </div>

      <div class="mb-12">
        <%= form.label :guest_email, :class => "form-label" %>
        <%= form.text_field :guest_email, :class => "form-control", :placeholder => "abc@example.com" %>
      </div>

      <div class="col-md-6">
        <%= form.label :arrival_date, :class => 'form-label' %>
        <%= form.datetime_field :arrival_date, :class => "form-control datepicker", :placeholder => "dd/mm/yyyy" %>
      </div>

      <div class="col-md-6">
        <%= form.label :departure_date, :class => 'form-label' %>
        <%= form.datetime_field :departure_date, :class => "form-control datepicker", :placeholder => "dd/mm/yyyy" %>
      </div>

      <div>
        <%= form.submit :class=> "btn btn-primary", :style=>"color: #fff;"%>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/edit.html.erb
<div class= "container">
  <h1>Editing Reservation</h1>

  <%= render 'form', reservation: @reservation %>

  <br>
  <%= link_to 'Show', @reservation, :class=>"btn btn-primary", :style=>"color: #fff;" %>
  <%= link_to 'Back', reservations_path, :class=>"btn btn-primary", :style=>"color: #fff;" %>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Reservations</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Hotel name</th>
        <th>Price</th>
        <th>Currency</th>
        <th>Arrival date</th>
        <th>Departure date</th>
        <th>Guest name</th>
        <th>Guest email</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.id %></td>
          <td><%= reservation.hotel_name %></td>
          <td><%= reservation.price %></td>
          <td><%= reservation.currency %></td>
          <td><%= reservation.arrival_date %></td>
          <td><%= reservation.departure_date %></td>
          <td><%= reservation.guest_name %></td>
          <td><%= reservation.guest_email %></td>
          <td><%= link_to '<i class="bi bi-eye"></i>'.html_safe, reservation %></td>
          <td><%= link_to '<i class="bi bi-pencil"></i>'.html_safe, edit_reservation_path(reservation) %></td>
          <td><%= button_to reservation, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')", :style=>"border: none; background-color: #fff;" do %>
              <i class="bi bi-trash" style="color: red;"></i>
          <% end%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Reservation', new_reservation_path, :class => "btn btn-primary", :style=>"color: #fff;" %>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <h1>New Reservation</h1>

  <%= render 'form', reservation: @reservation %>
  <br>
  <%= link_to 'Back', reservations_path, :class=>"btn btn-primary", :style=>"color: #fff;" %>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Reservation-<%= @reservation.id%></h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Hotel name</th>
        <th>Price</th>
        <th>Currency</th>
        <th>Arrival date</th>
        <th>Departure date</th>
        <th>Guest name</th>
        <th>Guest email</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @reservation.id %></td>
        <td><%= @reservation.hotel_name %></td>
        <td><%= @reservation.price %></td>
        <td><%= @reservation.currency %></td>
        <td><%= @reservation.arrival_date %></td>
        <td><%= @reservation.departure_date %></td>
        <td><%= @reservation.guest_name %></td>
        <td><%= @reservation.guest_email %></td>
        <td><%= link_to '<i class="bi bi-pencil"></i>'.html_safe, edit_reservation_path(@reservation) %></td>
        <td><%= button_to @reservation, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')", :style=>"border: none; background-color: #fff;" do %>
              <i class="bi bi-trash" style="color: red;"></i>
          <% end%></td>
      </tr>
    </tbody>
  </table>
  <%= link_to 'Back', reservations_path, method: :get, :class => "btn btn-primary", :style=>"color: #fff;" %>
</div>